sudo: false
language: python
cache:
  directories:
    - "~/.cache/pip"
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - py.test
  - flake8 camo_sign/
